### ISSUE TITLE
[Suggestion/Question] Option to make the enemy power bar hide when cast bar is shown.

### ISSUE THREAD

**Issue by Theryk** [Aviana/LunaUnitFrames#163]
Is there any easy way to make this? I manage to to do so on the first lunaunitframe version modifing some of the lua code but since 2.0 the code was rewritting and i dont know what triggers the hide/show bars anymore.

**Comment by Aviana** [comment]
Probably not that hard to do since version 2.xx isn't such a hack like 1.xx. But since i don't see the point other than simply emulating other frames that do this i won't waste any time on it. To be honest i think its more of a downgrade since you won't be able to see mana while a cast is going. But if someone makes a good implementation that has options to turn it off and the previous behavior as default, i might accept it into the code.
