### ISSUE TITLE
[bug] error: GetRaidRosterInfo

### ISSUE THREAD

**Issue by kakysha** [Aviana/LunaUnitFrames#189]
![image](https://cloud.githubusercontent.com/assets/822721/21427612/94294d56-c866-11e6-9595-11a0dc339dd9.png)

**Comment by Aviana** [comment]
I did not write RosterLib-2.0. And since its been used since 2006 without errors by a large number of other addons, i would guess that this is a private server related bug. The server might be sending conflicting information to the client causing this error. I would suggest using something like ImprovedErrorFrame. Also i would guess this error doesn't happen very often, does it?

**Comment by kakysha** [comment]
Yep, only once on Nost PvE, right after I joined WSG. Maybe somehow server messed sending bg players.
