### ISSUE TITLE
Skip auto attack after using clickcasting

### ISSUE THREAD

**Issue by googan** [Aviana/LunaUnitFrames#193]
Autoattack is switch off, when i'm using clickcasting. This is not very convenient, after each clickcasting (eg paladin purify in PVP), clicking on autoattack key...

**Comment by Aviana** [comment]
Even though you are clickcasting in vanilla you always change to the target you clicked, cast the spell and quickly switch back. Luna even pauses target updates during this process to minimize processing effort so there is next to no way of noticing it. Due to this process you stop attacking. I tried to save the attack status and restore it after the click casting reaquired the original target. It deems that doesn't work. Neither directly or the event that should signal that the attack stopped. I am out of ideas on this one.

**Comment by googan** [comment]
In addon Clique it works... auto attack does not stop after clickcasting. But Clique are not working with the Luna... Perhaps the solution to this issue can be found in Clique.

**Comment by Aviana** [comment]
Yes,Clique is supported. https://forum.elysium-project.org/index.php?showtopic=26742

However i will look into its code and see if i can adapt it.

**Comment by Aviana** [comment]
Fixed in master. Will be in next release.
