### ISSUE TITLE
[Suggestion] Separate(focus) group\frame.

### ISSUE THREAD

**Issue by vasecha** [Aviana/LunaUnitFrames#276]
Is there any chance to add such option in LUF? In the same way as it is implemented in sRaidsFrames Improved, where you can add any raid member to the separate frame.
Thank you in advance.

**Comment by Aviana** [comment]
There might be a chance that at some point i'll do a maintank group where you can manually add people to it. But development is slow at the moment due to me not finding time for it. So you might be better off using ORA2 at the moment. A focus like frame will most likely never happen. There are already other addons that do this and it would add another way too big part to this already monstrous addon. Also i don't like to put "guessing stuff" into this addon. Thats why Mobhealth, and Enemy debuff timers are not part of this.

**Comment by vasecha** [comment]
> There might be a chance that at some point i'll do a maintank group where you can manually add people to it

Yes, thats exactly what i meant. A separate column for raid frames only, a.k.a. "focus". Not the unitframes focus frame.
Something like this:
http://i.imgur.com/MCDuywf.jpg
(sRaidsFrames).
A lot of ppl would love this, no doubt. I hope youll find some time for it. 
Thank you in advance.
Cheer.

**Comment by Aviana** [comment]
Not spending any more effort into the legacy version.
