### ISSUE TITLE
Inc. heal indicator showing wrong target

### ISSUE THREAD

**Issue by lurexx** [Aviana/LunaUnitFrames#295]
Hi Aviana

The visual healing prediction on occasion pinpoints the wrong target.

For instance, I'm casting heals through the built in clickcasting, on occasion when I either move to cancel or use "SpellStopCasting()", and thereafter instantly cast on another target, it will show the incoming healing being cast on myself, instead of my target.

The issue occurred multiple times during the same raid, and I was able to reproduce the issue in a simple 2-3 member raid, by simply heal->cancel->heal-cancel on a raid member.

The issue is also visible to all other healers of the raid (all healers are required to use Luna in the guild I'm in, awesome addon, makes healing so much more pleasant)

I also tried to downgrade the healcomm lib to an older version (1,4), the issue still remained.

Thank you for reading this, great work!

**Comment by Aviana** [comment]
I don't see this issue:
https://webmshare.com/OyLaW

**Comment by rickyjohansson** [comment]
I got the same issue, sometimes it thinks im healing myself when in fact it is being cast on somebody else.
This did not happen with an older version of healcomm.

**Comment by lurexx** [comment]
Installed Luna on a fresh client the issue remains.

It happens at ~10sec and ~33sec 

https://vimeo.com/222221102

Hope this helps! cheers

**Comment by Barroth** [comment]
it is because sometimes the spellcastinginfo contains broken stuff, which doesnt get overwritten since broken stuff is not nil. Frequently happens on the first heal after shifting out of any druid form. Fixed it in my version by having CastSpellByName and CastSpell overwrite existing spellcastinginfo

**Comment by Aviana** [comment]
@Barroth got a line of code that you are referring to? What spellcastinginfo doesn't get overwritten?

**Comment by ItsmeAga** [comment]
likely fixed, now that ProcessSpellCast() overwrites the old stuff, and no longer keeps the values it already had

**Comment by Aviana** [comment]
As seen in the video this happens when very rapidly switching targets and casting. So this might be lag related and how the client fires events in that case. So i might not be able to fix this at all.

**Comment by lurexx** [comment]
I'm sorry to say, but the issue still remains. I had my friend try it too, he has the same problem.

**Comment by Aviana** [comment]
This will never be fixed, because the client doesn't react predictably to this kind of macro spamming. As some people have pointed out it boils down to having ProcessSpellCast() overwrite its old stuff or not. But since the right target is sometimes in the first call and sometimes in the later call (it gets calles multiple times when hammering buttons before the spell actually starts) it is impossible to determine which one is the correct one. Since the not overwriting variant seems to work with spamming the button on one target i will stick with that. It should provide better results for most people.

**Comment by Aviana** [comment]
If you recently downloaded 2.221 then please re-download it it has a crucial bug.
