### ISSUE TITLE
Suggestions: Enemy frames, focus frame, cooldowns and more

### ISSUE THREAD

**Issue by roanaes** [Aviana/LunaUnitFrames#302]
Hello I have two probably pretty big implementation suggestions, but would be really cool to see something similiar in luna as these addons(or maybe some sort of implementation of them?):

**https://github.com/zetone/enemyFrames**  
Similiar to raid frame, shows enemy frames in bgs

**https://github.com/wardz/FocusFrame** 
Adds a focus frame, familiar from newer expansions, doesnt work with luna atm

**https://github.com/shirsig/cdframes**
Adds cooldowns icons, would be cool to implement something similiar to luna so that you could choose their placement similiar to buffs/auras

**Also couple smaller suggestions:**
- Ability to move **debuffs**/auras inside the actual party frame much like in retail party frames.
- Ability to adjust size of text inside a line, for example with tags like [Size:14][size] or something like that, so that you could have different sizes of text for example inside the health bar.

I have a feeling that atleast the first suggestions above are probably insanely difficult to do, but just something that I find would be really cool to have so I though it's worth the shot :P **anyways thx for great addon!**

**Comment by Aviana** [comment]
There are several reasons why i won't copy the functionality of those addons over into mine.
- I would have nothing to add to those addons besides a uniform look and making these obsolete in the process.
- Hugely increasing the already big codebase of LUF. Making it even harder for me to maintain.
- I would find it disrespectful to the original authors.
- Some of these addons show speculative data. While i respect their efforts, i don't want to write an addon that could potentionally show incorrect stuff and then have people telling me that i have a faulty addon. I already have people constantly asking for a (reliable) 40y range check. And all castbars in LUF are kind of a prediction as well.

As for those 2 smaller suggestions...
- As for in-Line size changes in fonts: Every bit of text in WoW has a single size. So every time you would use such a tag it would mean i would have to create another test object and place it. And when you change it back the old test object would stay in memory until the game client is restarted. Not to mention all the handling i would have to do. So this would be a general no, not happening.
- I won't be touching Aura positions for a long time since i already did that recently. If i find time to work on this there will be a lot of other things i would do first.
