### ISSUE TITLE
Update broke the Critline addon

### ISSUE THREAD

**Issue by yarvaxea** [Aviana/LunaUnitFrames#380]
I updated from v.2200 to the latest v.2224 and for some reason it broke my Critline addon. When logging in it gives me this:
Error: Interface\AddOns\CritLine\CritLine.lua:506:attempt to call global 'COLOR' (a string value)

Tried to disable all other addons and it still gives me an error. 

I tried the other releases and v2222 is the latest one that works.

**Comment by Aviana** [comment]
This seems to be a conflict between the vanilla version of critline and the Tablet-2.0 library i use. Both appear to be using "COLOR" in the global namespace which breaks one of the two.
Since there is no easy fix for the library (due to complicated reasons) here is a fixed critline:
[CritLine.zip](https://github.com/Aviana/LunaUnitFrames/files/1958515/CritLine.zip)

**Comment by yarvaxea** [comment]
Oh you are the best, this works! BTW I did notice the same issue when I tried to get Bagnon working, eventually I found a custom version which worked. (Bagnon caused a lot of other errors too btw)
