### ISSUE TITLE
How to cancel aura (right click the buffs) during combat

### ISSUE THREAD

**Issue by Threemages** [Aviana/LunaUnitFrames#504]
Hello Aviana,

I would like to click off bloodrage sometimes to get off combat. However I just found that I cannot click off the buffs when I am in combat. 

I checked the code as :

![image](https://user-images.githubusercontent.com/35748782/65189437-f1bc7c80-da3e-11e9-9773-410aaa1c45a8.png)

So I delete InCombatLockdown() but still it doesn't work. Thank you!

Best,

**Comment by Aviana** [comment]
Being able to click off buffs in combat prevents the function of "make your own buffs bigger". Since canceling Bloodrage doesn't even drop you out of combat and clicking off Blessing of Salvation would be the only usecase i decided against it. Also there is still the solution of making a /cancelaura macro.
