### ISSUE TITLE
Buff and Debuff icons misplaced in Raid Frames

### ISSUE THREAD

**Issue by vindruvor** [Aviana/LunaUnitFrames#511]
As you can see on the screenshot below, the positioning of the buffs are completly misplaced on the raid frames, and same goes for Debuffs.

https://imgur.com/a/LJqTKXb

**Comment by Aviana** [comment]
No, they are placed under each frame and you have no space between your frames. The standard buffs / debuffs module is also not ideal for raidframes at the moment. I recommend the squares at this point in time.

**Comment by m00dymann** [comment]
So its not possible to have debuff trackers inside the raid frames? For healers that essential.

**Comment by Aviana** [comment]
Use the squares. They filter dispelables and stuff like Mortal strike can be added aswell.

**Comment by m00dymann** [comment]
![Lunaluna](https://user-images.githubusercontent.com/54237756/65467198-2fffd480-de61-11e9-9a3a-dda2d798fc44.png)
Debuff used in Picture is Polymorph
1. Cant get highlighting on dispellable debuffs to go away. 
2. Using the squares to track "Dispel" There is no option to see dispellable debuff textures, only the blue square. 
3. Can't get the option "Buff/Debuff to work without adding a ID, assume it's only for specific buffs? 
If so; Could you separate buffs and debuffs into 2 different options and make it so, if you don't enter the "Name (exact) or ID" field it will show every debuff/buff?

**Comment by Aviana** [comment]
1. I still can't reproduce that issue. Steps i took was:
- Only set the golden checkmark for debuff for highlight and border
- Get poisoned by a scorpion outside Org.
- Highlight / Border disappears after the debuff fades.
- Works as intended
2. I will add the option for texture since you requested it but the color always reflects which type of dispel is needed and since punishing dispels aren't a thing yet i didn't see the need for texture display.
3. Yes its for tracking specific buffs/debuffs and no i will not do it that way. A single square that shows the first buff / debuff is next to useless. I my own opinion you need to display at least 3 to make sense of them otherwise that stupid recently bandaged debuff will block the view of something more important. Instead i will fix the regular buff / debuff display that is used on non raidframes and make them a line that goes through the middle (buffs top, debuffs bottom) or along the top / bottom of the frame.

**Comment by m00dymann** [comment]
Healers can still not use these raid frames until we can see more than 1 debuff inside the frame.
The square function works great for the specific buffs/debuffs we need to track, PW:S, Rejuv, Fear Wards. or Lucifron's Dominate Mind. 
It worked great on the 1.12.1 version you revolutionzed healer frames with. We need it here too.

**Comment by Aviana** [comment]
I had to rewrite next to the entire addon from the p-server version. While i am glad i had beta access from the very start (otherwise this wouldn't exist at all) it will take more time to reach the same feature level as the 1.12 version. I mean i spend around 4 years on that.

**Comment by Aviana** [comment]
![Unbenannt](https://user-images.githubusercontent.com/425023/65833180-98b9d780-e2cd-11e9-9813-f2aabfa02fa0.png)
Just a preview...
