### ISSUE TITLE
HoTs as incoming heals

### ISSUE THREAD

**Issue by Eric-Johnston** [Aviana/LunaUnitFrames#514]
Is there any way to disable hots being shown as incoming heals? It's really not necessary when raid healing.

**Comment by Aviana** [comment]
The newest version limit hots to the next tick by default. I was under the impression that would be enough.

**Comment by Eric-Johnston** [comment]
I see that, but seeing HoTs represented as an incoming heal isn't particularly conducive to efficient raid healing. Healers shouldn't be making heal target decisions based on a HoT, especially with the way spell batching works in classic where a death takes priority over a heal in the same batch window.

**Comment by Aviana** [comment]
How is a hot tick that is coming in the next 3 seconds going to convince a healer not to heal. The amount its going to heal is clearly visible. There is no difference visible in the prediction between a castet downranked heal (because maybe the guy is oom) and a hot tick.
This seems more like a "make it because i want it" thing. I will add it eventually but i will give it a low prio.
