### ISSUE TITLE
HealComm

### ISSUE THREAD

**Issue by Darhole** [Aviana/LunaUnitFrames#609]
Hi Aviana,

I didn't know where else to put this because I have no way to contact you.

I was hoping you could bring back your Blizz UI HealComm with the new library, not sure on the logistics of that happening given the shit that went down, but here's hoping!

**Comment by GostMograine** [comment]
There's a wrapper going around that seems to work with Blizz UI:
https://github.com/LiuCJonathan/HealCommClassic/releases

I did a 10 minute test today, wasn't getting any LUA errors and nothing crashed. I was getting predicted heals both in Blizzard Raid Frames and Luna. Interested to see Aviana's opinion on this. Wonder if running both of these at the same time is a good idea or it doesn't matter at all.

**Comment by Aviana** [comment]
Yeah that guy seems to have picked up my GUI implementation for HealComm. Its just the frontend so there should be next to zero need for updates. The real work is done by the healcomm library. It is used by other addons like Luna, Elvui, etc as well so they can communicate with each other. So running them all at once doesn't matter because they all get their information from a shared lib.
