### ISSUE TITLE
Can you add the 5 second timer bar to the raid frame? [suggestion]

### ISSUE THREAD

**Issue by lvangh** [Aviana/LunaUnitFrames#637]
Can you add an option in Raid > to show the 5s rule on YOUR own player frame? 

It would be neat to have the option to show on other casters for post-analysis from video, but I was just thinking if you play with the player frame disabled and only look at your raid frames you can't see the 5s slider bar.

**Comment by Aviana** [comment]
I have looked into this and decided against it.

- The raidframes are cluttered enough as it is. Adding a moving bar or another indicator seems overkill to me. Besides there are other [#1](https://www.curseforge.com/wow/addons/fivesecondrule),[#2](https://www.curseforge.com/wow/addons/powermissing),[#3](https://www.curseforge.com/wow/addons/regen) addons to track this elsewhere.
- Tracking this on other players is next to impossible since all events regarding a successful casts from others are removed in classic. The 40y combatlog range limits this aswell.
