### ISSUE TITLE
Player and Target Frames Display Help

### ISSUE THREAD

**Issue by wtf119** [Aviana/LunaUnitFrames#67]
Hello Aviana / Rhenah,

First of all, I really appreciate your dedicated work on LUF, you are DA MAN!
Okay I will cut the crap. With the newest version of LUF, player and target frames display so different from the beta version. Please see the attached Pic one, thats the beta version style I used to play with(have hp/mana percent in two lines). On the other hand, Pic two is the style for current version.
So could you please tell me how to change the setting to bring my old style back? 
![1](https://cloud.githubusercontent.com/assets/15143408/10518259/27e7094a-7393-11e5-9310-5f36d4b64050.jpg)
![2](https://cloud.githubusercontent.com/assets/15143408/10518287/4818dbd0-7393-11e5-95cc-208e55a1e8fe.png)

**Comment by Aviana** [comment]
Try putting "[perhp]%                                           [smarthealth]" in the right box. Also it looks like you deleted some of the tags...

**Comment by wtf119** [comment]
Thanks so much for your quick reply. 

First, according to your instruction, I made the health bar of Player Frames back to my old style, but I can't make it for mana bar. 

Second, this method did not work for Target Frames (as shown on the attached pic). 
And how can I let  "creature type" (Beast, Undead, Demon, Humanoid etc.) info showing on the second bar of Target Frames? Can you make a GUI menu for this kind of setting in the future version?

Finally, what do you mean by "deleted some of the tags"? I just download the zip file from https://github.com/Aviana/LunaUnitFrames and the file is 1.01MB. Do I miss something?

**Comment by wtf119** [comment]
![3](https://cloud.githubusercontent.com/assets/15143408/10524179/c7afb69e-73b0-11e5-9146-2d133b9939a6.jpg)
![4](https://cloud.githubusercontent.com/assets/15143408/10524192/d4277ac4-73b0-11e5-87b1-16d56386c23c.png)

**Comment by Aviana** [comment]
Try putting more spaces between the % and [smarthealth]. And i don't mean tags on github. I'm calling things like [smarthealth] tags. They are a description of what information should be displayed on the frame. I put that in to allow people to build their own text because everyone wanted something different. So everyone can build it they way they want.

If you select the powerbar there should be "[levelcolor][level][shortclassification] [classcolor][smartclass]" in the field "Left Text and "[pp]/[maxpp]" in the field "Right Text" If it already is you have to select a different font from the general options since the current one doesn't support your language.

That might be a general problem anyway since i know for certain that there are some functions in my mod that won't work on a non english client since i am unable to do correct translations for all languages.

**Comment by wtf119** [comment]
Thank you for clarify my issue. It seems like my non English client messed up some functions of LUF. 
Actually the "Powerbar" can display class name and creature type in the old beta version of non English client, but somehow it didn't work in the latest version even with the right tags on. 
Anyway thanks again for all the work and best wishes to you : ) 
![isuuse1337](https://cloud.githubusercontent.com/assets/15143408/10547069/a1d1ee38-7464-11e5-8a44-9580dad5b4ca.png)
