### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [Aviana/LunaUnitFrames#762]
I love Luna, but I have extreme fear around using addons that are no longer in active development. I am just curious as to the status of the addon - if it is no longer being actively developed, I'd prefer to rip the band-aid off early and move to a new unit frame now as opposed to when I encounter some kind of unresolvable issue

**Comment by Aviana** [comment]
It has been this quiet because i have essentially rewritten the entire addon to be able to publish it on Overwolfs Curseforge. It will be based on oUF, has all the existing features, has a lot of the outstanding issues/features fixed/added. However as i aim for it to be a drop in replacement i still need to adress the following:

- 1 feature
- 3 bugs
- Localization
- Settings migration

**Comment by pedrorafaelpadilla** [comment]
Thank you for the transparency!
