### ISSUE TITLE
Stutter Problem when tracking raid buff/debuffs

### ISSUE THREAD

**Issue by smoothys** [Aviana/LunaUnitFrames#813]
When tracking too many buff/debuffs in Squares the game starts to heavily stutter in raid combat.
As soon as combating ends the stuttering starts to get better.

https://www.youtube.com/watch?v=gG2E5rccUsY&feature=youtu.be

I was tracking this list in one Square, the whole string.
Fear;Terrifying Roar;Psychic Scream;Intimidating Shout;Sleep;Wyvern Sting;Howl of Terror;Bellowing Roar;Terrify;Terrifying Howl;Intimidating Roar;Panic

After disables the Square the combat was smooth again.

**Comment by Lipovske** [comment]
Had this problem also. Once I started tracking certain debuffs in naxx to show on my raid frames I had constant stutters when mobs would die. Had to switch to a different unit frame addon for the first time in years been using LUNA since Nostalrius. Really unfortunate as this feature works on the new unit frames I am using and doesn't cause a stutter.

Caused me so much headache too since this can really only be tested while in a raid and it is tough to troubleshoot problems while trying to raid at the same time.

**Comment by Aviana** [comment]
Please try 4060 there should be a lot less lag now.

**Comment by Aviana** [comment]
Also please use #775 for further discussion.
