### ISSUE TITLE
Buff Timers and NPC Health Bars

### ISSUE THREAD

**Issue by Methos611** [Aviana/LunaUnitFrames#822]
I have yet to switch from using version 3.XXX to version 4.XXX because of the buff timer size increase which is not editable and now is just too large and messy. As well as the NPC health bar color change which I thought was address in a previous update but is still purple instead of green and you can't change it. Are there plans to address these issues in future releases?

Thank you

![Luna](https://user-images.githubusercontent.com/81266656/112223277-124f2f00-8c00-11eb-9609-9a20d3ec731c.png)

**Comment by Aviana** [comment]
The timer text is not made by Luna. You have to set it up in an addon like OmniCC.
The color is this way because the fallback color is called "static" and can be found under status colors. You can set it to any color you want. Or you color the healthbar by reaction which would make friendly NPCs green. This can also be adjusted under reaction.
I simply can't replicate the system 1 to 1 like it was before because oUF dictates it this way. Also i don't think that its unreasonable to work this way.
